locator:
  image: apachegeode/geode:1.11.0
  container_name: geode-locator
  hostname: geodelocator
  mem_limit: 512m
  expose:
   - "10334"
   - "1099"
   - "7070"
  ports:
   - "1099:1099"
   - "10334:10334"
   - "7070:7070"
  command: >
    bash -c 
      "gfsh start locator --name=`hostname` \
       --mcast-port=0 \
       --hostname-for-clients=localhost \
       --jmx-manager-hostname-for-clients=localhost \
       && tail -n 100 /`hostname`/`hostname`.log \
       && \
       while true; do \
         sleep 10; \
       done"

server:
  image: apachegeode/geode:1.11.0
  container_name: geode-server01
  hostname: geodeserver01
  mem_limit: 2g
  links:
   - locator:geodelocator
  expose:
   - "8080"
   - "40404"
   - "1099"
  ports:
   - "40404:40404"
  volumes:
   - ./config:/config/:ro
  command: >
    bash -c 
      "until gfsh start server --name=`hostname` \
       --locators=geodelocator[10334] \
       --server-port=40404 \
       --cache-xml-file=/config/cache.xml \
       --hostname-for-clients=localhost \
       --max-heap=1G; \
       do \
         sleep 3; \
       done \
       && tail -n 100 /`hostname`/`hostname`.log \
       && \
       while true; do \
         sleep 10; \
       done"
